service: vicalert-proxy

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2
  memorySize: 128
  timeout: 10
  stage: ${opt:stage, 'prod'}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  proxy:
    handler: proxy.handler
    events:
      - http:
          path: /proxy
          method: get
          cors: true